dist: trusty
sudo: required 
language: cpp

services:
  - docker
before_install:
  - docker pull qbradq/example-build:latest
  - docker run -itd --name build qbradq/example-build
  - docker exec build git clone https://github.com/victormafra/pegSolitaire.git /repo

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake .
  - cmake --build . -- -j2
  - docker exec build cmake -H/repo -B/build
  - docker exec build cmake --build /build
  - docker exec build cmake --build /build --target run-tests
  
after_success:
  - docker exec build /repo/codecov.sh
